### ISSUE TITLE
Color Picker in Popup Resets to Default on Reopen

### ISSUE THREAD

**Issue by EmreKb** [fatihsen-dev/mercimek#1]
I noticed an issue with the color picker in the popup. When I select a custom color for changing the commit background color, it works fine initially. However, when I close and reopen the popup, the selected color resets back to the default instead of retaining the previously chosen color.

**Comment by fatihsen-dev** [comment]
Hi @EmreKb thank you for the feedback, I will fix it as soon as possible, if you want, you can fix it and send a pr request.

**Comment by fatihsen-dev** [comment]
https://github.com/fatihsen-dev/mercimek/commit/f79e9e0ba71388a656e6d383fbe09a9de0a8df11 https://github.com/fatihsen-dev/mercimek/pull/2/commits/ba055c86e8e712b1db034de6ac754e3cc2618004
